Update credits and dependancies
FiguraMC/Figura pull request #1
Opened 2023-07-15 22:02 UTC by superpowers04

e

2023-07-15 22:08 UTC, skyrina requested changes
change KOTMGit to MoonlightGit, remove isHamburger api, modify discord invite to https://discord.gg/nbN8KZyhUq

2023-07-15 22:08 UTC, skyrina commented on src/main/resources/fabric.mod.json
also also modify the discord invite link to https://discord.gg/nbN8KZyhUq

2023-07-15 22:08 UTC, skyrina commented on src/main/java/org/moon/figura/lua/api/entity/EntityAPI.java
also remove the isHamburger api entirely please

2023-07-15 22:08 UTC, skyrina commented on src/main/java/org/moon/figura/FiguraMod.java
could you change KOTMGit to MoonlightGit here?

2023-07-15 22:21 UTC, skyrina approved these changes

2023-07-15 22:22 UTC, skyrina commented
Since there are two pull requests that are the same thing, I have googled "random number from 1 to 2" and it said 2, so I'm going to merge https://github.com/Moonlight-MC-Temp/Figura/pull/2.

2023-07-15 22:27 UTC, skyrina commented
reopened by request

2023-07-16 11:49 UTC, Kichura reviewed
To be superseded in #4.

2023-07-16 22:34 UTC, closed without merging