Animated emojis, and armor rendering crash fix
FiguraMC/Figura pull request #48
Opened 2023-08-02 01:10 UTC by omoflop

title

2023-08-03 20:22 UTC, Covkie commented
If anyone has no objections ill merge this

2023-08-05 23:19 UTC, UnlikePaladin commented
Why is this removing the GoL easter egg without mentioning it anywhere?

2023-08-05 23:21 UTC, UnlikePaladin commented
If anything debug mode should be a regular config option on the settings screen and not be hidden behind a key combo that is famously used for easter eggs

2023-08-05 23:38 UTC, UnlikePaladin requested changes, later dismissed
The rest of the changes relating to animated emojis look good to me, just these minor things.

2023-08-05 23:38 UTC, UnlikePaladin commented on fabric/src/main/java/org/figuramc/figura/config/fabric/ModMenuConfig.java
> +        return parentScreen -> new ConfigScreen(parentScreen, Configs.DEBUG_MODE.value);
You forgot to change this to your FiguraMod.debugModeEnabled()

2023-08-05 23:38 UTC, UnlikePaladin commented on common/src/main/java/org/figuramc/figura/gui/screens/AbstractPanelScreen.java
> +            Configs.DEBUG_MODE.setValue("true");
Might as well make it a regular option on the screen, it doesn't need to be hidden behind a key combo. We already expose several options normal users don't mess with like the ip backend option.

2023-08-05 23:38 UTC, UnlikePaladin commented on common/src/main/java/org/figuramc/figura/FiguraMod.java
> +        return b;
you do know you could simplify this entire method to
```suggestion
   return b == true;
```
lol

2023-08-07 03:34 UTC, omoflop commented
@UnlikePaladin thanks for the feedback, will fix all that stuff 👍

2023-08-08 23:48 UTC, merged